### ISSUE TITLE
File names incorrect and empty when loaded to mIRC

### ISSUE THREAD

**Issue by ghost** [Heep123/Heepsbot#1]
The file names are different to those found in the loader script, i.e missing .ini and extra dashes.

After the names are corrected they're also missing all content, they're loaded in blank.

**Comment by Glyciant** [comment]
Scripts aren't currently supposed to be downloaded from GitHub. The scripts are stored elsewhere so they download with the correct names and file extensions. This may change soon though :)

**Comment by Glyciant** [comment]
Solved :)
