### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bossmanwizard** [Heep123/Heepsbot#6]
Hi, im new to coding. So how do I actually do this? I pasted this in "Remote" script then what? Do I need to change something? If yes, please tell me :)

**Comment by Glyciant** [comment]
You shouldn't need to change anything, unless the command docs specifically say to do so :)

**Comment by bossmanwizard** [comment]
I want to welcome new followers and to do so, do I at least need to change something?

**Comment by Glyciant** [comment]
Oh, I see. Refer to row 185 on https://docs.google.com/spreadsheets/d/1dDGOu8Y9WAzHTL-fgvWWws8lZyggEJYbAgcjCDFqG7c/edit#gid=1814746144.
