### ISSUE TITLE
You do not have permission to redistibute JSON For mIRC

### ISSUE THREAD

**Issue by SReject** [Heep123/Heepsbot#8]
In [/Remote/Core.ini](https://github.com/Heep123/Heepsbot/blob/70a0833ca5ca365b9e06102efa0807359849cb98/Remote/Core.ini) you include a copy of [JSON for mIRC](https://github.com/SReject/JSON-For-Mirc/tree/v0.2.4) of which stipulates in the [notes section](https://github.com/SReject/JSON-For-Mirc/tree/v0.2.4#notes--) that it is not to be redistributed. Instead remove the file and link to its [Release Page](https://github.com/SReject/JSON-For-Mirc/releases/tag/v0.2.41-beta) for users of your script(s) to download.

**Comment by Glyciant** [comment]
Done!
